Add no-test check

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -4,11 +4,6 @@ run_tests=''
 running_all=false
 export TEST_DIR="$(cd "$(dirname "$0")" && pwd)"
 
-if [[ ! -e "${TEST_DIR}/fakeproc" ]]; then
-    echo "Extracting test proc file system..."
-    tar -C "${TEST_DIR}" -xf "${TEST_DIR}/fakeproc.tar.gz"
-fi
-
 if [[ -z ${@} ]]; then
     running_all=true
     run_tests=$(ls -1 ./tests/??-*-*.sh);
@@ -19,6 +14,11 @@ for num in ${@}; do
     test_file=$(ls -1 ./tests/${test_name}-*-*.sh)
     run_tests="${run_tests}${test_file}"$'\n'
 done
+
+if [[ -z "${run_tests}" ]]; then
+    echo "Error: no tests to run."
+    exit 1
+fi
 
 points=0
 total_points=0
